service: ft-webhook-to-discord
variablesResolutionMode: 20210326

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  lambdaHashingVersion: 20201221

  # you can overwrite defaults here
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

  # you can define service wide environment variables here
  environment:
    DISCORD_BOT_TOKEN: ${ssm:/ft-webhook-to-discord/${self:provider.stage}/DISCORD_BOT_TOKEN}
    DISCORD_CHANNEL_ID: ${ssm:/ft-webhook-to-discord/${self:provider.stage}/DISCORD_CHANNEL_ID}

package:
  exclude:
    - "*"
    - "*/**"
  include:
    - src/**/*.py

functions:
  event:
    handler: src.handler.send_event
    events:
      - httpApi:
          path: /event
          method: post

plugins:
  - serverless-better-credentials
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
  defaultStage: dev
